#### Numpy is one of the libraries in python that is used to perform numerical operations for data science

In [4]:
import numpy as np #this imports numpy so that the functions can be accessed

In [8]:
my_list = [2,4,5,6,7,8,9,1,0]    # creating a list

In [9]:
my_list

[2, 4, 5, 6, 7, 8, 9, 1, 0]

In [10]:
np.array(my_list)  # calling an array so that the list can be turned int an array

array([2, 4, 5, 6, 7, 8, 9, 1, 0])

In [11]:
my_list2 = [[1,2,3], [2,3,4], [5,6,7], [8,9,0]]

In [13]:
listed = np.array(my_list2)

In [14]:
listed

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7],
       [8, 9, 0]])

In [15]:
type(my_list2)

list

In [17]:
type(listed) # checks the type of listed

numpy.ndarray

In [18]:
np.arange(0,50) # generates a range of numbers from 0 to 49

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [19]:
# a range function can take in a third argument called th step size, i.e the increment or iteration

In [20]:
np.arange(0,50, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [25]:
np.arange(20,0,-2) # you can also decrease the value but it has to start with a bigger number

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Arrage functions

In [26]:
np.zeros(5)   # 0 in 5 places in a row

array([0., 0., 0., 0., 0.])

In [27]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [34]:
np.zeros((2, 3)) # This is to generate two dimenstional array i.e 2 x 3 (rows, column)

array([[0., 0., 0.],
       [0., 0., 0.]])

### Linspace is used to print out 10 equally sapced values from 0 to 5, it can be any number, it is used to generate a linearly spaced values 

In [35]:
np.linspace(0,1,50) # This give 50 equally spaced value between 0 and 1

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [14]:
a = np.linspace(0,1,101)

In [15]:
a

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [19]:
newA = list(filter(lambda x:x != 0., a))

In [22]:
np.array(newA)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [23]:
np.array(newA).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
np.array(10,10)

In [36]:
np.linspace(0, 8, 3)

array([0., 4., 8.])

In [45]:
np.linspace(2, 20, 4)  # Count the step size to get the linearly spaced value 

array([ 2.,  8., 14., 20.])

In [46]:
np.linspace(2, 26, 5)# Between 2 and 26, we have 5 points that can be spaced without decimals

array([ 2.,  8., 14., 20., 26.])

In [47]:
np.linspace(2, 26, 4)

array([ 2., 10., 18., 26.])

In [48]:
np.linspace(2, 26, 3)

array([ 2., 14., 26.])

### To create an identity matrix , (the diagonals have same values of 1)

In [37]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
np.eye(5) # 5 x s matrix with diagonals of one

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## The next line gives a set of 5 uniformly spaced values fro 0 to 1

In [39]:
np.random.rand(5)  # gives 5 equally spaced values between 0 to 1

array([0.47013297, 0.1012715 , 0.31528758, 0.8718884 , 0.01571822])

In [3]:
np.random.rand(1)

array([0.25972624])

In [40]:
np.random.rand(5, 5)  # gives 5 equally spaced values in an array of 5 X 5 between 0 to 1 

array([[0.09480221, 0.2377257 , 0.31092326, 0.3478028 , 0.88170545],
       [0.47437177, 0.4647936 , 0.67318072, 0.51355387, 0.27913356],
       [0.64631252, 0.20064306, 0.17010361, 0.04994675, 0.47522384],
       [0.44219923, 0.14172075, 0.9857872 , 0.93893401, 0.26037487],
       [0.8073564 , 0.91656705, 0.3937594 , 0.58682799, 0.93847829]])

In [4]:
np.random.rand(10, 10)

array([[0.08123126, 0.51962284, 0.09887979, 0.04032607, 0.24235375,
        0.59522173, 0.74583444, 0.0677891 , 0.96492808, 0.44415854],
       [0.996955  , 0.65620212, 0.89085383, 0.43754828, 0.19676967,
        0.8404702 , 0.59526848, 0.39933399, 0.66027071, 0.20767635],
       [0.62804172, 0.81240973, 0.26397222, 0.20382105, 0.0778198 ,
        0.5710065 , 0.90059765, 0.37539538, 0.07176539, 0.36310123],
       [0.83003992, 0.59386449, 0.82005841, 0.66003062, 0.75191568,
        0.6945309 , 0.75238481, 0.33489502, 0.75131582, 0.0150668 ],
       [0.96054395, 0.97808196, 0.82185398, 0.66419943, 0.39071908,
        0.70368364, 0.98526834, 0.90624159, 0.74733331, 0.96391235],
       [0.13937141, 0.55147638, 0.96434427, 0.08530854, 0.09345902,
        0.18228191, 0.41377796, 0.86696522, 0.83781895, 0.58360009],
       [0.83256989, 0.93358776, 0.62277891, 0.13826762, 0.00434688,
        0.31051057, 0.76164539, 0.84642411, 0.60342025, 0.43912968],
       [0.10543175, 0.40988512, 0.8330916

In [41]:
np.random.rand(2, 5)  # gives 5 equally spaced values in an array of 2 X 5 between 0 to 1 

array([[0.30071969, 0.55386291, 0.75417501, 0.33069372, 0.19227074],
       [0.32646191, 0.26209511, 0.08931841, 0.2635809 , 0.11816213]])

## Read up on Normal Distribution

### Gives 10 random integers inclusive on the low end and exclusive on the high end

In [49]:
np.random.randint(1, 100, 10) #generates 10 random numbers between 1 and 100 

array([59, 24, 68, 34, 59, 46, 49, 99, 63, 74])

In [51]:
arr = np.arange(25)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
b = np.arange(30)

In [73]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [56]:
b.reshape(5,5)

ValueError: cannot reshape array of size 16 into shape (5,5)

In [57]:
b.reshape(4,4) # this reshapes it to 4 x 4 matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
b.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [59]:
b.reshape(1,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [77]:
arr.max()

24

In [82]:
c = np.random.randint(1, 100,10 )

In [83]:
c

array([45, 48, 80,  1, 97, 72, 24, 51, 32,  9])

In [84]:
c.min()  #  returns the minimum value of a random number in the array

1

In [85]:
c.argmax()  #  returns the position of the maximum value of a random number

4

In [86]:
c.argmin() #  returns the position of the minimum value of a random number

3

In [87]:
c.max() #  returns the maximum value of a random number in the array

97

# Numpy Indexing and selection

In [97]:
a = np.arange(11)

In [98]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## The ability of numpy array to broadcast

In [99]:
arr = np.arange(0,25)

In [100]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [101]:
slice_arr = arr[10:18]

In [102]:
slice_arr

array([10, 11, 12, 13, 14, 15, 16, 17])

In [105]:
slice_arr[:] = 100

In [106]:
slice_arr

array([100, 100, 100, 100, 100, 100, 100, 100])

In [107]:
arr #note that the changes also occur in the original array

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100, 100, 100,
       100, 100, 100, 100, 100,  18,  19,  20,  21,  22,  23,  24])

# Indexing a two dimensional array (Matrices)

In [108]:
arr_2d = np.array (([5,10,15], [20,25,30], [35,40,45]))

In [109]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [110]:
arr_2d[1][2]  # 30 is at row 1 column 2

30

#### Comparison operators can also be used on any array and perform arithmetric operations